version: '3.4'

services:
  soyyo_back:
    image: co.com.soyyo.entity.filter-dev-1_0_0
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
    - 5000:5000
    environment:
      - API_URL=https://awovcw7p76.execute-api.us-east-1.amazonaws.com/dev/entity/v2.1
